theme: jekyll-theme-cayman

title: Zhixingzhehui (association of learners)
description: Zhixingzhehui (association of learners)
locale: en-US
author: Zhixingzhehui (association of learners)
plugins: [jekyll-sitemap]
timezone: Asia/Shanghai
future: true
sass:
  style: compressed

lsi: true
profile: true

defaults:
  - scope:
      path: ""
    values:
      layout: "functional"
  - scope:
      path: "_posts"
    values:
      layout: "novel"
      author: Zhixingzhehui (association of learners)
      locate: en-US
      cc-type: by-nc
      permalink: /post/:categories/:title/
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
 - README.MD
 - CONTRIBUTING.MD
 - CODE_OF_CONDUCT.MD
 - Gemfile
 - Gemfile.lock
 - temp

i18n:
  About us: 关于我们
  Book intro: 书本介绍
  Reading list: 书单推荐
  Spotlight: 集锦分享

nav-shortname:
